apiVersion: apps/v1
kind: Deployment
metadata:
  name: mp1-test-app
  labels:
    app: mp1-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mp1-test-app
  template:
    metadata:
      labels:
        app: mp1-test-app
    spec:
      containers:
        - name: mp1-test-app
          image: mp1-test-app
          ports:
            - containerPort: 80
          env:
            # MEC Platform endpoint
            - name: MEC_BASE
              value: "http://172.17.0.2"
            # Application instance identifier
            - name: APP_INSTANCE_ID
              value: "997fc80a-cfc1-498a-b77f-608f09506e86"
      imagePullPolicy: IfNotPresent