FROM ubuntu:20.04

RUN useradd -m -d /home/mec_app mec_app
WORKDIR /home/mec_app

COPY app.py app.py
COPY requirements.txt requirements.txt
COPY app_site /var/www/

RUN apt-get update; apt-get install -y python3 python3-pip


USER mec_app
RUN pip3 install -r requirements.txt

CMD python3 app.py
